spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/ffs?serverTimezone=UTC&characterEncoding=utf8
      username: root
      password: 123456
      initial-size: 3
      min-idle: 3
      max-active: 10
  redis:
    #Redis数据库索引（默认为0）
    database: 1
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 2333
    password:
    lettuce:
      pool:
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000
        max-idle: 8
        min-idle: 0
  http:
    encoding:
      charset: utf-8
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:/mapper/ffs/*.xml
  type-aliases-package: com.ffs.entity

userRedis: 25920

jwt:
  secret: LinRunPeng
  expires: 30
server:
  tomcat:
    uri-encoding: UTF-8
